name: hsma_forecast3
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=2.1.2
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - scipy=1.4.1
  - seaborn=0.10.0
  - statsmodels=0.11.1
  - pip:
    - tensorflow==2.3.1
    - forecast-tools==0.1.5
