name: hsma4_forecast9c
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - python=3.8.8
  - scipy=1.4.1
  - seaborn=0.11.2
  - statsmodels=0.11.1
  - pip:
    - tensorflow==2.7.0
    - forecast-tools==0.1.6
